# Generated by Django 2.2.7 on 2019-11-16 04:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wc_app2', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='grade',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('grade_name', models.CharField(default='未命名班级', max_length=16)),
            ],
        ),
    ]
